apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-config
  namespace: testdr
data:
  # application selectors for the app
  # should follow convention from:
  # https://portal.nutanix.com/page/documents/details?targetId=Nutanix-Data-Services-for-Kubernetes-v1_2:top-app-cr-manual-create-cli-k8s-t.html
  config: |
    {
      "app_configs": [
        {
          "source_namespace": "testdr",
          "target_namespace": "testdr",
          "replication_target_name": "replication-nkp-manager-dr-remote",
          "create_if_not_exists": true,  
          "app_name": "testdr-application",
        }
      ]
    }
