apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-config
data:
  # application selectors for the app
  # should follow convention from:
  # https://portal.nutanix.com/page/documents/details?targetId=Nutanix-Data-Services-for-Kubernetes-v1_2:top-app-cr-manual-create-cli-k8s-t.html
  config: |
    {
      "app_configs": [
        {
          "source_namespace": "",
          "target_namespace": "",
          "replication_target_name": "",
          "app_name": "",
          "create_if_not_exists": true, # use this option if you want the recipe to create the Application CR
          # use 'application_selector' with the 'create_if_not_exists': true option
          # if you want the recipe to create the Application CR with application selectors.
          # The source of truth is always the Application CR. If the app_selector specified
          # here (app selector in config file) conflicts with the Application CR,
          # the app_selector in the Application CR will be the source of truth.  
          "application_selector": {
            "resourceLabelSelectors": [
              {
                "labelSelector":
                  {
                    "matchLabels":
                      {
                        "app": "wordpress"
                      }
                  }
                }
              ]
          },
        }
      ]
    }
