apiVersion: v1
kind: ConfigMap
metadata:
  name: reset-replication-config
data:
  config: |
    {
      "app_configs": [
        {
          "target_namespace": "",
          "app_pplan_name": "",
          "app_pplan_uid": "", # optional
          "app_snapshot_name": "", # use this for out of band snapshot.
          
          # if files_protection_policies is provided, only these frp's are considered for reset replication.
          "files_protection_policies": [
            "",
            ""
          ]

        }
      ]
    }
