apiVersion: dataservices.nutanix.com/v1alpha1
kind: ReplicationTarget
metadata:
  name: replication-dr-remote
  namespace: testdr
spec:
  namespaceName: testdr
  remoteName: dr-remote
  serviceAccountName: default
