apiVersion: dataservices.nutanix.com/v1alpha1
kind: ProtectionPlan
metadata:
  name: testdr-sync-protection-plan
  namespace: testdr
spec:
  protectionType: sync
  replicationConfigs:
    - replicationTargetName: replication-dr-remote
